services:
  tenshi:
    build:
      context: .
      args:
        PASSWORD: ${TENSHI_PASSWORD:?error}
    container_name: tenshi
    hostname: tenshi
    environment:
      - PASSWORD=${TENSHI_PASSWORD:?error}
      - VNC_PASSWORD=${TENSHI_VNC_PASSWORD:?error}
      # Optionally uncomment to enable OpenCV debugging:
      # - DEBUG_OPENCV=1
    ports:
      # FastAPI
      - "6081:8000"
      # Browser remote debugging port
      - "6082:9222"
      # noVNC HTML5 interface and raw VNC (for debugging)
      - "6080:6080"
      - "5900:5900"
    volumes:
      - /dev/shm:/dev/shm
      - /run/dbus/system_bus_socket:/host/run/dbus/system_bus_socket
      - ./docker/data:/tenshi/data
    cap_add:
      - SYS_PTRACE
    restart: on-failure
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
